'use strict';
const { parse } = require('pgsql-ast-parser');
const MAX_ROWS = Math.max(1, Math.min(Number(process.env.AI_SQL_MAX_ROWS || 100), 500));
const VIEW_COLUMNS = Object.freeze({
  ai_public_task_details:['task_id','task_name','task_type','status','is_active','last_checked','target','url','notification_contacts','host_mapping_enabled','host_mapping_hostname','host_mapping_ip','total_checks','failure_count','availability_percent','open_incident','incident_started_at','latest_failure'],
  ai_public_task_check_history:['task_id','task_name','task_type','checked_at','result','response_ms','error_sanitized'],
  ai_public_incident_timeline:['task_id','task_name','task_type','status','incident_started_at','l1_sent_at','l2_sent_at','l3_sent_at','last_l3_repeat','alerted_tiers','latest_failure'],
  ai_public_application_logs:['created_at','level','category','task_name','message_sanitized','detail_sanitized'],
  ai_public_administrator_contacts:['email','role'],ai_public_host_mappings:['task_id','task_name','hostname','ip_address','enabled'],
  ai_authenticated_response_analytics:['task_id','task_name','task_type','period_start','sample_count','average_ms','minimum_ms','maximum_ms','p95_ms'],
  ai_authenticated_user_activity:['created_at','actor','action','detail_sanitized'],
  ai_superadmin_audit_summary:['action','event_count','first_event_at','last_event_at'],ai_superadmin_user_accounts:['email','role','created_at'],
  ai_superadmin_archives:['archive_date','filename','category','size_bytes','created_at'],ai_superadmin_mail_diagnostics:['created_at','level','message_sanitized','detail_sanitized'],
  ai_superadmin_system_health:['active_tasks','fault_tasks','open_incidents','checks_last_24h','backend_uptime_seconds'],
  ai_superadmin_task_configuration:['task_id','task_name','task_type','target','url','expected_status','timeout_sec','os_type','interval_min','failure_threshold','l2_delay_min','l3_repeat_min','notification_contacts','email_enabled','is_active','status','cfc','host_mapping_enabled','host_mapping_hostname','host_mapping_ip','created_at','updated_at']
});
const PUBLIC=['ai_public_task_details','ai_public_task_check_history','ai_public_incident_timeline','ai_public_application_logs','ai_public_administrator_contacts','ai_public_host_mappings'];
const AUTH=[...PUBLIC,'ai_authenticated_response_analytics','ai_authenticated_user_activity'];
const SUPER=[...AUTH,'ai_superadmin_audit_summary','ai_superadmin_user_accounts','ai_superadmin_archives','ai_superadmin_mail_diagnostics','ai_superadmin_system_health','ai_superadmin_task_configuration'];
function allowedViews(scope){return new Set(scope==='SUPERADMIN_READ_ONLY'?SUPER:scope==='AUTHENTICATED_READ_ONLY'?AUTH:scope==='PUBLIC_READ_ONLY'?PUBLIC:[]);}
function walk(value,visit){if(!value||typeof value!=='object')return;visit(value);for(const item of Object.values(value))Array.isArray(item)?item.forEach(v=>walk(v,visit)):walk(item,visit);}
function validateQuery(plan,scope){if(!plan||typeof plan!=='object'||Array.isArray(plan))throw error('AI_INVALID_SQL_PLAN');const sql=String(plan.sql||'').trim(),parameters=plan.parameters;if(!sql||sql.length>12000||!Array.isArray(parameters)||parameters.length>50)throw error('AI_INVALID_SQL_PLAN');if(sql.includes(';')||/--|\/\*|\*\//.test(sql))throw error('AI_UNSAFE_SQL');let statements;try{statements=parse(sql)}catch{throw error('AI_INVALID_SQL')};if(statements.length!==1)throw error('AI_UNSAFE_SQL');const root=statements[0],ctes=new Set();if(root.type==='with'){for(const b of root.bind||[]){ctes.add(String(b.alias?.name||'').toLowerCase());if(b.statement?.type!=='select')throw error('AI_UNSAFE_SQL')}}else if(root.type!=='select')throw error('AI_UNSAFE_SQL');const allowed=allowedViews(scope),relations=new Set(),refs=[];walk(root,node=>{if(node.type==='table'&&node.name?.name)relations.add(String(node.name.name).toLowerCase());if(node.type==='ref'&&node.name&&node.name!=='*')refs.push(String(node.name).toLowerCase());if(node.type==='call'){const fn=String(node.function?.name||node.function||'').toLowerCase();if(/pg_|dblink|lo_import|lo_export|sleep|set_config|current_setting/.test(fn))throw error('AI_UNSAFE_SQL')}});for(const relation of relations)if(!ctes.has(relation)&&!allowed.has(relation))throw error('AI_VIEW_NOT_ALLOWED');if(!relations.size)throw error('AI_VIEW_NOT_ALLOWED');const aliases=new Set();walk(root,node=>{if(node.alias?.name)aliases.add(String(node.alias.name).toLowerCase())});const approvedColumns=new Set([...relations].flatMap(r=>VIEW_COLUMNS[r]||[]));for(const alias of aliases)approvedColumns.add(alias);for(const ref of refs)if(!approvedColumns.has(ref)&&!['true','false'].includes(ref))throw error('AI_COLUMN_NOT_ALLOWED');const indexes=[...sql.matchAll(/\$(\d+)/g)].map(m=>Number(m[1])),max=indexes.length?Math.max(...indexes):0;if(max!==parameters.length||new Set(indexes).size!==max)throw error('AI_PARAMETER_MISMATCH');let executable=sql;const select=root.type==='with'?root.in:root;if(!select.limit)executable=`SELECT * FROM (${sql}) AS ai_limited_result LIMIT ${MAX_ROWS}`;else{const lim=select.limit.limit;if(lim?.type==='parameter'){const i=Number(String(lim.name).replace('$',''))-1;if(!Number.isInteger(parameters[i])||parameters[i]<1)throw error('AI_INVALID_LIMIT');parameters[i]=Math.min(parameters[i],MAX_ROWS);}else if(lim?.type==='integer'||lim?.type==='numeric'){if(Number(lim.value)>MAX_ROWS)throw error('AI_INVALID_LIMIT');}}return{sql:executable,parameters,purpose:String(plan.purpose||'Approved read-only query').slice(0,1000),expectedColumns:Array.isArray(plan.expectedColumns)?plan.expectedColumns.map(String).slice(0,100):[],relations:[...relations].filter(r=>!ctes.has(r)),maxRows:MAX_ROWS};}
function error(code){return Object.assign(new Error(code),{code,status:422})}module.exports={validateQuery,allowedViews,VIEW_COLUMNS};
